// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLyRtBVvW0fXTFR6GbQILeY98My8NhQak',
    appId: '1:172661240357:web:3af158ba5df8592d8485cc',
    messagingSenderId: '172661240357',
    projectId: 'get-dog',
    authDomain: 'get-dog.firebaseapp.com',
    storageBucket: 'get-dog.appspot.com',
    measurementId: 'G-NGC2CZ2TXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9OBYvRPof7Mw-3ssea7PpW118cUfLYk',
    appId: '1:172661240357:android:66a9c6a56a768fb18485cc',
    messagingSenderId: '172661240357',
    projectId: 'get-dog',
    storageBucket: 'get-dog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxlHgFnwhzMPY0Yvfx9jO4x1Ld_IMpsyg',
    appId: '1:172661240357:ios:c145dd3ec047f2d98485cc',
    messagingSenderId: '172661240357',
    projectId: 'get-dog',
    storageBucket: 'get-dog.appspot.com',
    iosClientId: '172661240357-7gg3pm3tdklg7airdjlj5dn6vqsnnkat.apps.googleusercontent.com',
    iosBundleId: 'com.getpet.getpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxlHgFnwhzMPY0Yvfx9jO4x1Ld_IMpsyg',
    appId: '1:172661240357:ios:c145dd3ec047f2d98485cc',
    messagingSenderId: '172661240357',
    projectId: 'get-dog',
    storageBucket: 'get-dog.appspot.com',
    iosClientId: '172661240357-7gg3pm3tdklg7airdjlj5dn6vqsnnkat.apps.googleusercontent.com',
    iosBundleId: 'com.getpet.getpet',
  );
}
